---
bibliography: references.bib
title: Introduction

author: # one line per author
- Marcus Specht

abstract: ""

execute: 
  echo: false
---

## Why this book ? {#intro}

There are plenty of good books on research methods for different disciplines, so why another one?


One starting point was the development of a MOOC on multi-disciplinary research methods for engineers in 2020. With this MOOC we tried to give a simplified introduction to research methods on which participants could build. The MOOC targeted to give participants a good understanding of where to start and what are the decisions you have to make in a research project on human-computer systems in general. Nevertheless when looking for reference materials on which learners could build we did not find open content chapters to give a simple but comprehensive overview on many methods and research instruments. The aim of this book is to fill this gap and become and online repository with simple introductions to important decisions in a research project and primers for research methods in the different phases of the research project.

A second issue was the long ongoing discussion of the TEL community on how to develop a flexible approach and strategy for doing Technology Enhanced Learning Research coming from different starting points and disciplinary backgrounds [@kalz2014].

In this book we look at the research process in different phases with different objectives and these can of course overlap and also loop in different designs and implementation in research projects dependent on their objectives and approach. Nevertheless in the discussion with the editorial team we identifed several key questions and parts we consider essential in a good research project which are mainly the following:


## How to use this book?

  This book and its chapters cna be seen as ac primer for research methods. On the one hand it aims to give you a high quality overview on specific methods and how to perform and implement them as also what their contribution in a bigger research design can be. So if you are new to a method or you consider using it in your research design you should defintely scan the relevant chapter and get an overview of the specific method as also the necessary relevant knowledge and competences. Furthermore even if you are an experienced research we love to get feedback to the chapters and enhance them and add online discussions.

## Overview of the research process and methods introduced

### Developing a strategy

When starting up a new research project the mostv essntial issues is to clearly identify your research questions and challenges you want to focus on. In the best case you have a clear problem and challenge with which you start and can identify the courses of the problem and the different components that play a role.

   Problems and research questions?

  What is the difference between a problem, a challenge, a research question and a hypothesis? This chapter will introduce different types of research questions how to develop them and how to relate them to underlying problems, theories and data collection.

   Theoretical Modelling and Conceptual Frameworks (MOOC)

  You conceptual model is the basis for all your research work, it defines dependent and independent variables and their relations. It specifies the main components of your research questions and gives an idea how to operationalise them as also what performance is done by participants in your research and what you will measure dependent from the different treatments.

   Choosing the appropriate method (MOOC)

Different methods can help you to answer different parts of your research questions and will contribute with different insights and eveidence to a bigger research questions. In this chapter you will learn to differentiate between methods, their potential contribution as also their shortcomings.
 

   Mixed Method Designs (MOOC)
   Most research questions in interdisciplinary fields combine different methods from explorative and scoping research, qualitative methods and quantiative methods. This chapter will give you a primer on how to combine different methods and for what purpose.

### Understanding previous work

To understand previous work and what other researchers have already found and identifed as relevant evidence for your research journey. There are different ways to look at existing research and different ways how to use the published data. As one of the most prominent approaches literature reviews collect a body of publications or evidence and structure or evaluate it according to given schemes or research questions. Nevertheless literature reviews come in different flavours and are used for different purposes and also can develop different research results.

TODO [ ] insert definition of meta analysis and simulations

Literature reviews
There are different versions and purposes of literature reviews a good over view of the different types is given in [@pare_synthesizing_2015]. This actually differentiates 9 different types of literature reviews and describes these according to ...


  - Meta Analysis
  - Simulations

### Engaging with stakeholders
  - Prototyping
  - Focus groups
  - Group concept mapping

### Formative methods
  - Task performance studies
  - Piloting

### Summative methods
  - Quasi experimental studies
  - Lab experiments
  - Field studies

- Research project cases and short descriptions


## Research methods for whom?

This book is for students of every age and background which enjoy learning about these topics. One scenario is bachelor and master students which have to do a research project in there studies. Some of the foundations chapters should give them a primer for the structure and decisions to make to come to a study design. On the other hand this is also for multi year research settings as in a PhD project or other projects.

The focus of this book is on research methods that are used to understand human-computer systems mostly in the field of learning and teaching with technology. Of course the methods are helpful, useful and can be applied in other domains but this is the main focus.

## How to use this book?



## References {-}




## code and graphics examples collection



```{mermaid}
graph LR
    A(Understanding the problem, challenge, target, objective, context) --> D(Select your research approach)
    B(What are the affordances of the technology) --> D
    C(What is your practical problem you start with) --> D
    D --> E(Defining your research question)
    E --> F(Design Based Research)
    E --> G(Participatory Design)
    E --> H(Educational Research)
    F --> I(Result)
    G --> I(Result)
    H --> I(Result)
```

```{r eval=TRUE, echo=FALSE}
library("DiagrammeR")
DiagrammeR("
  graph LR
    A-->B
    A-->C
    C-->E
    B-->D
    C-->D
    D-->F
    E-->F
")
```

